function AboutPage() {
  return (
    <div className='text-center p-10'>
      <h1 className='text-2xl font-bold my-4'>About</h1>
      <p className='text-gray-300'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Modi provident architecto dicta dolorem, aut voluptates possimus quos similique? Quidem asperiores similique, rerum saepe consectetur optio, earum ea quasi repudiandae ab eaque tempore rem quisquam ad eius voluptatibus tenetur commodi quod vel. Fugit omnis voluptatum cupiditate iusto tenetur? Illum fugit voluptate id dolor quae autem magni eum ad beatae maiores at sunt quam minus voluptas corrupti magnam sint rerum alias veritatis eligendi distinctio esse, dolores laudantium repudiandae. Culpa unde eum nesciunt saepe quibusdam blanditiis eius quis nam sequi sapiente, libero molestiae dolore praesentium inventore delectus corrupti aliquid laborum reiciendis quidem. Dolore dolor placeat, dolorem doloremque iusto doloribus deleniti, cum earum sit vero quae consequatur repudiandae impedit, ipsa totam. Blanditiis qui eligendi similique assumenda quidem aliquam ea quae nesciunt magni dolor itaque laudantium odit, quos accusamus ad illum harum quisquam molestiae totam consequuntur. Perspiciatis amet cupiditate possimus eligendi eveniet distinctio debitis perferendis delectus in vitae? Quis iure neque quibusdam vitae obcaecati, nostrum culpa modi veritatis pariatur blanditiis, ut enim veniam ullam ex distinctio dolore minus ipsam. Perferendis modi numquam sapiente corrupti nulla. Dicta at commodi esse iure minus? Doloremque nam nihil dignissimos saepe. Harum, voluptate nulla nam quis fugiat quasi suscipit. Labore amet, nostrum fuga dolore eos quibusdam, quasi harum possimus accusamus at in, totam asperiores explicabo natus. Rem tempore odit harum, aliquid maiores voluptas illum atque vel unde architecto veritatis deserunt voluptates voluptatem beatae animi repellendus similique. Facere sint iure nostrum vitae in eveniet tenetur dolore debitis pariatur. Voluptatem voluptatum, dolore voluptates praesentium debitis rem fugit possimus ea quod eum quas vero similique excepturi. Perspiciatis deserunt error modi optio. Atque eligendi maxime consequuntur id, adipisci ab eos inventore facere ad nostrum, quo, quis odit suscipit. Non reiciendis similique et nemo saepe molestias vero ex totam ducimus hic! Doloribus ad neque natus.</p>
    </div>
  )
}

export default AboutPage